### ISSUE TITLE
Program shows only a black window

### ISSUE THREAD

**Issue by extrowerk** [pulkomandy/beniccc#2]
This is with current 64 bit nightly, legacy boot, intel extreme.

**Comment by pulkomandy** [comment]
demo or benchmark mode? or both?

**Comment by extrowerk** [comment]
In both case.

**Comment by pulkomandy** [comment]
How do you run it? Apparently it needs scene1.bin in the current directory, which is not great. I'll move that to a resource instead.

**Comment by extrowerk** [comment]
That could be the reason, let me check.

**Comment by extrowerk** [comment]
I moved the executable to the top level folder, where the .bin and the .mod file is, but still just hangs. Can't even close, just kill it.

**Comment by pulkomandy** [comment]
I just pushed changes to put the polygon stream inside the executable. However apparently it crashes due to a memory corruption in ffmpeg/libopenmpt (no crash if I use a music in a different format). But it should at least solve your problem.

**Comment by extrowerk** [comment]
Now the graphics shows up, but then crashes. According to debugger it is not crashed in openmpt code. I hovewer just updated the openmpt recipe to the current one (your program still crashing..)

**Comment by pulkomandy** [comment]
Yes, it crashes in BWindow, but only when I use a MOD file. With a flac file instead (or no music) it's all fine.
